name: android_dynamic_icon
description: A flutter plugin for dynamically changing multiple android app icons for your app.
version: 1.0.0
homepage: https://github.com/
repository: https://github.com/
issue_tracker: https://github.com/

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_plugin_android_lifecycle: ^2.0.28

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.example.android_dynamic_icon
        pluginClass: AndroidDynamicIconPlugin
